### ISSUE TITLE
Multiple types of messages/responses

### ISSUE THREAD

**Issue by ghostdogpr** [scalaz/scalaz-actors#6]
Currently actors are designed as `Actor[+E, -A, +B]`.
Let's say we want our actor to handle 2 types of messages and return a different response type for each.
```
sealed trait Msg
case class Msg1() extends Msg
case class Msg2() extends Msg

sealed trait Resp
case class Resp1() extends Resp
case class Resp2() extends Resp
```
We want to return a `Resp1` when we receive a `Msg1` and a `Resp2` when we receive a `Msg2`.

If we have an Actor[E, Msg, Resp], there is no guarantee for the caller about which subtype it will receive.

The way Akka Typed solved this is by having an ActorRef[T] `replyTo` as part of the message if a reply is needed. If we restrict ourselves to a single node, this is similar to passing a promise as part of the message:
```
case class Resp1()
case class Resp2()

sealed trait Msg
case class Msg1(p: Promise[Nothing, Resp1]) extends Msg
case class Msg2(p: Promise[Nothing, Resp2]) extends Msg
```

So we can have a simple Actor[+E, -A] that returns Unit, and might complete given promises when handling messages.

@jdegoes @softinio and others:
Do you see other possible designs? How do you think we should handle this case?

**Comment by jdegoes** [comment]
This would require re-imagining actor as:

```scala
trait Actor[+E, -F[+_], +G[+_]] {
  def ! [A](fa: F[A]): IO[E, G[A]]
}
```

Then you have:

```scala
sealed trait Msg[A]
case class Msg1() extends Msg[Resp1]
case class Msg2() extends Msg[Resp2]

case class Resp1()
case class Resp2()
```

Then you have `actor: Actor[E, Msg, Id]` (where `type Id[A] = A`), Now when you call `actor ! Msg1()`, you know you get back `Resp1`.

In general this would add the ability to have actor responses tied to their input messages.

**Comment by ghostdogpr** [comment]
I love the idea!

I'm trying to adapt the original gist but I'm having issues with the fact that Promise is invariant in type A. That means I'm unable to have a queue of `(F[_], Promise[E, G[_]])` , and then offer a `(F[A], Promise[E, G[A]])`.
Will keep trying different things but let me know if I'm missing something.

**Comment by jdegoes** [comment]
@ghostdogpr Can you open up a ticket on ZIO and we'll take a look?

**Comment by ghostdogpr** [comment]
I finally made it work.
Had to use a type alias `type PendingMessage[E, F[_], A] = (F[A], Promise[E, A])` to express that the message and the promise have the same type parameter.

The only thing that's bothering me now is that IntelliJ finds errors that don't exist (SBT compiles fine) in the message processing logic, which is not great since it's the code that library users will have to write. 
```
def getResp[A](msg: Msg[A]): A = msg match {
    case Msg1() => Resp1()
    case Msg2() => Resp2()
  }
```
`Expression of type Resp1 doesn't conform to expected type A`

Anyway I will clean the solution and submit a PR.

**Comment by ghostdogpr** [comment]
Here's the PR: https://github.com/scalaz/scalaz-actors/pull/7

**Comment by jdegoes** [comment]
@regiskuckaertz Yes, that would be nice! It should be possible even without invariance, or even with the more recent change of making the input type an `F[_]` (although "standard" type class instances cannot be created).

**Comment by ghostdogpr** [comment]
@regiskuckaertz 
That sounds interesting! I had a look at ZIO Schedule that seems to have similar semantics.

In your example, what would be the type of `actor`? `Actor[E, Either[Msg1, Msg2], [Either[Rsp1, Rsp2]]`?
Then how do you go from that to have a `def ! (fa: Msg1): IO[E, Rsp1]` for sending a message to the actor while keeping guarantees about the response type?

**Comment by regiskuckaertz** [comment]
Yes 😃 I would image that `+++` would create an actor with the following semantics:
```scala
def +++(a1: Actor[Msg1, Rsp1], a2: Actor[Msg2, Rsp2]) = Actor {
  def !(a: Either[Msg1, Msg2]) : IO[E, Either[Rsp1, Rsp2]] = a match {
    case Left(m) => (a1 ! m) map Left(_)
    case Right(m) => (a2 ! m) map Right(_)
  }
}
```
modulo the correct types, i.e. `Msg1[Rsp1]`)

**Comment by ghostdogpr** [comment]
I like the principle but I wonder how this could be transparent for the caller.
When sending a `Msg1`, receiving a `Either[Rsp1, Rsp2]` (or more complex if we compose more actors) is not telling exactly what message type it is, even though there's only one possible.

**Comment by regiskuckaertz** [comment]
Yeah, this would become unwieldy when you have an actor made of more than a couple of others 😨

This could be solved with a left-biased `Inject`:
```scala
trait Inject[A, B] { def inj(a: A): B }
def identity[A] = new Inject[A, A] { def inj(a) = a }
def left[A, B] = new Inject[A, Either[A, B]] { def inj(a) = Left(a) }
def right[A, B, C](implicit I: A Inject B) = new Inject[A, Either[C, B]] { def inj(a) = Right(I.inj(a)) }
```
Now you can write:
```scala
trait Actor[Msg, Rsp] {
  def ![Msg0, Rsp0](a: Msg0[Rsp0])(implicit I: Inject[Msg0, Msg]): IO[E, Rsp0] = ???
}
```

**Comment by softinio** [comment]
@ghostdogpr @jdegoes @regiskuckaertz 

PR #7 was merged. Catching up on the rest of this conversation, did we agree on any further improvements to be made since the  merge of that PR? 

Thanks!

**Comment by ghostdogpr** [comment]
Having composable actors would be nice but I haven’t come up with the good formula that addresses these issues:
- the return type of the send function should be the actual type so that there’s no downcasting to do for the caller
- the composed actor needs a unified mailbox, otherwise messages won’t be processed one by one in the order they arrived

But I think the initial problem is solved: now each message type can have a dedicated response type. We can open a new ticket for composable actors.
